### ISSUE TITLE
Create  controlers for the database

### ISSUE THREAD

**Issue by Anna-Livia** [bitterMargaritas/SpendingSpree#1]
https://www.codementor.io/olatundegaruba/nodejs-restful-apis-in-10-minutes-q0sgsfhbd

Create controllers to create and display users

**Comment by lorenrh** [comment]
other reference worth looking at

https://medium.com/of-all-things-tech-progress/5-steps-to-build-a-rest-api-in-node-js-with-mongodb-e1f2113a39bd
