### ISSUE TITLE
After creating a user, the user is not displayed

### ISSUE THREAD

**Issue by lorenrh** [bitterMargaritas/SpendingSpree#2]
Created a user with a post method:

```
curl -X POST --header "Content-Type: application/json" -d '{"name":"Lorena", "amountOwed":300}' http://localhost:3000/users
```

And when trying to list user from 

localhost:3000/users/lorena

should display something

**Comment by Anna-Livia** [comment]
Here is a tutorial to learn how to use mongodb and node js
https://code.tutsplus.com/articles/an-introduction-to-mongoose-for-mongodb-and-nodejs--cms-29527
